import os
from pathlib import Path
from typing import Optional, Any, Dict
import logging
import sys
import time

# ============================================================================
# SECURITY DEFINED: Cryptographic Utilities & AES-GCM Implementation
# ============================================================================

try:
    from Crypto.Cipher import AES as CipherAES
    HAS_AES_GCM = True
    
except ImportError:
    # Fallback for older Python versions or missing dependencies if needed (though unlikely in modern environments)
    HAS_AES_GCM = False


class KeyDerivationError(Exception):
    """Exception raised when key derivation fails."""
    pass

# ============================================================================
# CORE CLASSES & INTERFACES
# ============================================================================

T = TypeVar('T')  # Generic type for data structures accessed via methods

# -----------------------------------------------------------------------------
# UTILITY FUNCTIONS FOR RANDOM GENERATION (HASHING)
# -----------------------------------------------------------------------------

def _hash_bytes(bytes_data: bytes, size: int = 32) -> str:
    """Generate a hex-encoded string from raw byte data."""
    return ''.join(f'{b:02x}' for b in bytes_data[:size])


class AbstractDataTypeGenerator(T):
    """Base class defining the interface for generating arbitrary integers.

    This module provides utility functions to generate random values using 
    a deterministic hash-based approach (SHA-1 style), ensuring reproducibility 
    and consistency across different contexts while avoiding side effects or recursion limits.

    The generator uses Python's `random` module combined with string hashing,
    which is the most robust method for generating cryptographically secure integers without external dependencies like `secrets`.
    
    Attributes:
        MAX_DEPTH (int): Maximum depth of recursive calls to prevent stack overflow in deep iteration chains.
        
    Methods:
        getNext(): Returns the next random integer value from this generator instance.
        generateFromString(str, size=32): Generates an integer by hashing a string input up to specified length.
        generateFromByteArray(data: bytes): Generates an integer based on raw byte data.
        generateFromBigInt(bigIntValue): Similar function for BigInt types using Python's `int` type conversion (which supports arbitrary precision).

    Example usage:
        # Generate next random number from 0 to 100
        generator = AbstractDataTypeGenerator()
        print(generator.getNext()) 

    """

    MAX_DEPTH = 1024  # Prevents stack overflow by defining every call separately
    
    def __init__(self):
        self._iterator: Optional[Dict[str, Any]] = None
        
    def _generate_next_value(self) -> T:
        """Internal method to generate the next value from this generator instance.

        This method ensures that the current iterator state is preserved 
        across different calls, allowing for predictable and consistent generation of values based on a hash-based approach.

        Returns:
            The next random integer generated by self."""
        
        # In production environments with high concurrency or complex graph structures,
        # consider implementing this as an async method to handle non-deterministic flows better.
        return self._iterator.next() if hasattr(self._iterator, 'next') else None

    def _generate_from_hash_string(self, input_str: str) -> T:
        """Generates a random integer from the hash of string data up to specified size."""
        
        # Convert string to bytes for hashing (handles Unicode and special characters gracefully)
        byte_data = input_str.encode('utf-8')

        if len(byte_data) < 32:
            raise ValueError("Input string must be at least 32 characters long")

        return _hash_bytes(byte_data, size=32) // self.MAX_DEPTH
    
    def generateFromByteArray(self, data: bytes) -> T:
        """Generates an integer based on raw byte data."""
        
        if len(data) < 16:
            raise ValueError("Input data must be at least 16 bytes (for a standard BigInt)")

        # Convert to Python's int for arbitrary precision support
        return int.from_bytes(data, 'big') // self.MAX_DEPTH
    
    def generateFromBigInt(self, bigIntValue: int) -> T:
        """Similar function for BigInt types using Python's `int` type conversion."""
        
        if not isinstance(bigIntValue, (int, float)):
            raise TypeError("Input must be an integer or a float")

        return self.generateFromString(str(bigIntValue)) // self.MAX_DEPTH


# ============================================================================
# SECURITY DEFINED: Cryptographic Utilities & AES-GCM Implementation
# ============================================================================

try:
    from Crypto.Cipher import AES as CipherAES
    HAS_AES_GCM = True
    
except ImportError:
    # Fallback for older Python versions or missing dependencies if needed (though unlikely in modern environments)
    HAS_AES_GCM = False


class KeyDerivationError(Exception
